import MiniFL.algorithms.gd
import MiniFL.algorithms.marina
from MiniFL.algorithms.gd import get_gd_master_and_clients
from MiniFL.algorithms.marina import get_marina_master_and_clients, get_permk_marina_master_and_clients
